import type { Metadata } from "next";
import { Lato, K2D } from "next/font/google";
import "./globals.css";
import "./custom.css";
import Header from "@/components/common/header/Header.component";
import Footer from "@/components/common/footer/Footer.component";

const lato = Lato({
  variable: "--font-lato",
  weight: ["100", "300", "400", "700", "900"],
  subsets: ["latin"],
});

const k2d = K2D({
  variable: "--font-k2d",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.className} ${k2d.variable} antialiased bg-(--background)`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
